name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # A cada 12 horas (formato corrigido)
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}  
          svg_out_path: dist/github-snake.svg

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: gh-pages  # Branch padrão para GitHub Pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
