name: Update GitHub Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: snake
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: github-contribution-grid-snake.svg
          gif_out_path: github-contribution-grid-snake.gif
          force_update: true

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-contribution-grid-snake.svg
          git commit -m "Update snake animation [skip ci]"
          git push
